// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOQEvyIQOydgZwoKg8KVNeToZVHVZLYRc',
    appId: '1:110636428281:web:6d4b6283728e904212ab28',
    messagingSenderId: '110636428281',
    projectId: 'wv-recipe-app',
    authDomain: 'wv-recipe-app.firebaseapp.com',
    storageBucket: 'wv-recipe-app.appspot.com',
    measurementId: 'G-3BFXXR523P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJphhWmIq7X7TuPJbcvF4zBihATTrwinw',
    appId: '1:110636428281:android:cbe1ef09021da4a412ab28',
    messagingSenderId: '110636428281',
    projectId: 'wv-recipe-app',
    storageBucket: 'wv-recipe-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrB6mkaUTDabhRRfNvjD-3VAbzdiPFzO4',
    appId: '1:110636428281:ios:ab0298cdbea3ec5612ab28',
    messagingSenderId: '110636428281',
    projectId: 'wv-recipe-app',
    storageBucket: 'wv-recipe-app.appspot.com',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBrB6mkaUTDabhRRfNvjD-3VAbzdiPFzO4',
    appId: '1:110636428281:ios:ab0298cdbea3ec5612ab28',
    messagingSenderId: '110636428281',
    projectId: 'wv-recipe-app',
    storageBucket: 'wv-recipe-app.appspot.com',
    iosBundleId: 'com.example.recipesApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOQEvyIQOydgZwoKg8KVNeToZVHVZLYRc',
    appId: '1:110636428281:web:5ab4ecc5f513a00f12ab28',
    messagingSenderId: '110636428281',
    projectId: 'wv-recipe-app',
    authDomain: 'wv-recipe-app.firebaseapp.com',
    storageBucket: 'wv-recipe-app.appspot.com',
    measurementId: 'G-DG1VLJJYGM',
  );
}
